### ISSUE TITLE
Favicon Lacking Background Transparency

### ISSUE THREAD

**Issue by travelton** [gravitational/docs-website#5]
The favicon is not transparent, leading to a white background:
![Image](https://github.com/user-attachments/assets/db558c13-1751-4e19-8041-675ac8a2e68a)

I recommend using the favicon from the marketing site... It was previously updated to fix this. 
https://goteleport.com/favicon.ico

**Comment by roraback** [comment]
@ptgott @travelton We swap a light and dark theme version in the web product. Might be good to do the same in the marketing site and docs, too.
Difference in dark theme is that the product favicon is much clearer, especially when hovering:
 ![Image](https://github.com/user-attachments/assets/32761438-f4b2-4e37-ab8f-ae62f970a18d)
![Image](https://github.com/user-attachments/assets/3f9d8dc0-f8f4-4fe6-82ba-7cd13094f8b4)
![Image](https://github.com/user-attachments/assets/57aaaf5e-fb43-4465-884e-3afd9e4cb6ee)

We used [pngs](https://drive.google.com/drive/folders/1dm6iH3ZphKFVIrr6MTMlp8XqzzhgH7pL?usp=drive_link) in the product, since they're [supported by much older browsers](https://caniuse.com/link-icon-png) than we support for the product, but I'm not sure whether the marketing site has broader requirements.

**Comment by ptgott** [comment]
I've opened #30 to reconfigure the favicon. For some reason, the ICO icon does not have a transparent background on the Docusaurus site, while the SVG icon does. The icon files are identical to the ones used in `gravitational/docs`. I've just suggested changing the Docusaurus config to use their default HTML templating.
